# Generated by Django 2.2.16 on 2021-11-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_comment_is_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default=1, help_text='Заголовок нового поста', max_length=256, verbose_name='Заголовок'),
            preserve_default=False,
        ),
    ]
