# Generated by Django 2.2.16 on 2021-12-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.TextField(blank=True, default=2),
            preserve_default=False,
        ),
    ]
